name: Qt Build Project

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3

    - name: Clone repository
      uses: actions/checkout@v2

    - name: Build project
      run: |
           ls -la
           pwd
           qmake && make -j$(nproc)
