name: Qt Build Project

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Qt
      uses: francoislavergne/qt-build-action@v2
      with:
        qt-version: '5.15.2'
        architecture: 'x64'
        os: 'ubuntu'

    - name: Build project
      run: qmake && make -j$(nproc)
